language: node_js
node_js:
  - 10
notifications:
  email:
    on_success: never
script:
  - yarn run lint
  - yarn run test
cache:
  directories:
    - node_modules
after_success:
  - yarn run coveralls
